
version: 2

models:
    - name: dim_customer
      description: "Customer table"
      columns:
          - name: C_CUSTKEY
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
sources:
  - name: sample_db
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: CUSTOMER
      - name: LINEITEM